test

diff --git a/.github/workflows/azure-webapps-node.yml b/.github/workflows/azure-webapps-node.yml
--- a/.github/workflows/azure-webapps-node.yml
+++ b/.github/workflows/azure-webapps-node.yml
@@ -28,6 +28,18 @@ jobs:
           npm run build --if-present
           npm run test --if-present
 
+      - name: Print environment variables
+        env:
+          VITE_DISABLE_SAVE: ${{ vars.VITE_DISABLE_SAVE }}
+          VITE_CLERK_PUBLISHABLE_KEY: ${{ vars.VITE_CLERK_PUBLISHABLE_KEY }}
+        run: |
+          echo "VITE_DISABLE_SAVE=$VITE_DISABLE_SAVE"
+          echo "VITE_CLERK_PUBLISHABLE_KEY=$VITE_CLERK_PUBLISHABLE_KEY"
+          if [ "$VITE_CLERK_PUBLISHABLE_KEY" != "false" ]; then
+            echo "Failed"
+            exit 1
+          fi
+
       - name: Upload artifact for deployment job
         uses: actions/upload-artifact@v4
         with:
